# Generated by Django 6.1.1 on 2026-09-19 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import care.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("specialty", models.CharField(max_length=120)),
                ("provider", models.CharField(max_length=180)),
                ("scheduled_for", models.DateTimeField()),
                ("status", models.CharField(default="scheduled", max_length=30)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("ecg", "ECG"),
                            ("lab", "Lab report"),
                            ("prescription", "Prescription"),
                            ("imaging", "Imaging"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("provider", models.CharField(max_length=180)),
                ("recorded_on", models.DateField()),
                ("summary", models.CharField(blank=True, max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("pending", "Pending")],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=care.models.medical_record_path,
                        validators=[care.models.validate_medical_file],
                    ),
                ),
                ("plain_language_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("dosage", models.CharField(max_length=80)),
                ("prescribed_by", models.CharField(blank=True, max_length=160)),
                ("prescribed_on", models.DateField()),
                ("active", models.BooleanField(default=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-active", "-prescribed_on"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reference_id", models.CharField(max_length=32, unique=True)),
                ("reason", models.CharField(max_length=180)),
                ("requested_by", models.CharField(max_length=160)),
                ("referring_provider", models.CharField(max_length=180)),
                ("receiving_provider", models.CharField(max_length=180)),
                ("receiving_clinician", models.CharField(max_length=160)),
                ("priority", models.CharField(default="Routine", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Consent required"),
                            ("approved", "Consent approved"),
                            ("shared", "Shared"),
                            ("received", "Received"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_records",
                    models.ManyToManyField(
                        blank=True, related_name="referrals", to="care.medicalrecord"
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_name", models.CharField(max_length=160)),
                ("organization", models.CharField(max_length=180)),
                ("action", models.CharField(max_length=200)),
                ("occurred_at", models.DateTimeField()),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="care.referral",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
    ]
