# Generated by Django 6.1.1 on 2026-09-20 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import care.models


def preserve_legacy_referring_clinician(apps, schema_editor):
    referral = apps.get_model("care", "Referral")
    referral.objects.filter(created_by__isnull=True, clinician__isnull=False).update(
        created_by_id=models.F("clinician_id")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("care", "0002_referral_clinician"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="clinical_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="referral",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            preserve_legacy_referring_clinician,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="referral",
            name="diagnosis",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="referral",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="referral",
            name="specialty",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="referral",
            name="priority",
            field=models.CharField(
                choices=[("Routine", "Routine"), ("Urgent", "Urgent"), ("Emergency", "Emergency")],
                default="Routine",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="reference_id",
            field=models.CharField(
                default=care.models.generate_referral_reference_id, max_length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="requested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
