# Generated by Django 6.1.1 on 2026-09-19 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("patient", "Patient"), ("clinician", "Clinician")],
                        default="patient",
                        max_length=20,
                    ),
                ),
                ("caretrace_id", models.CharField(max_length=24, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=30)),
                ("blood_group", models.CharField(blank=True, max_length=8)),
                ("allergies", models.CharField(blank=True, max_length=200)),
                ("conditions", models.CharField(blank=True, max_length=250)),
                ("emergency_contact_name", models.CharField(blank=True, max_length=120)),
                ("emergency_contact_relationship", models.CharField(blank=True, max_length=80)),
                ("organization", models.CharField(blank=True, max_length=180)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
